# Generated by Django 3.0.12 on 2021-03-15 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0002_auto_20210315_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likeuser_set',
            field=models.ManyToManyField(blank=True, related_name='likeuser_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
